In [2]:
import numpy as np
list1 = [1,2,3]
arr1 = np.array(list1)


print(arr1 + 2)


[3 4 5]


In [ ]:
type1 = np.array([2,4.3,6.965,45.6,56.66,1,44], int) # same work with differnt method and syntax for np.array is np.array(argument,datatype)
print(type1)
print(type(type1))

In [ ]:
type1.dtype # To check datatype of the array.

In [ ]:
type1.shape # To check shape(Rows,Column) of the array.

In [ ]:
type1.size

In [ ]:
type1.itemsize # It tells you how much memory, in bytes, is occupied by one element of the array. 

In [ ]:
2 in type1 # In statement checks whether the value is present in array or not , return True if present otherwise False.

In [ ]:
7 in type1

In [ ]:
type1 = np.array([[2,4.3,6.965,45.6,56.66,1,44]], dtype = "int")  # same work with differnt method
print(type1)  # output will come as a 2D that we can recognized by just looking 2 brackets means 2D or we can run type1.ndim
print(type(type1))

In [ ]:
marv = np.array([1,2,3,'4.0',5]) # presence of string element in an array ,converts all the element in string too(Homogemous array)
print("Array marv: ",marv)

In [ ]:
mb = np.array([1,2,3.98,4,5]) # presence of float element in an array ,converts all the element in float too(Homogemous array)
print("Array mb: ",mb)

In [ ]:
mar = np.array([1,2.66,3,'4.0',5]) # presence of string and float element in an array ,converts all the element in string too(Homogemous array)
print("Array mar: ",mar)   # gives priorty to string when string and float both are present in array.

In [ ]:
arr2 = np.arange(11,1,-1)
print(arr2)

print(type(arr2))

In [ ]:
import numpy as np
arr3 = np.random.randn(3,4) # we can give shape or order(Rows,Columns) for array for e.g (3,4) = 3*4 = 12 so 12 random values will get produced.
arr3   # By default datatype for random values is float.

In [ ]:
import numpy as np
arr3 = np.array(np.random.randn(9),dtype = "int")  # we can put the number for the data we want in array for 9 it will give 9 elements randomly.
arr3 # we can get the random values of the dataype we want by puting it explicitily. 

In [ ]:
import numpy as np
arr3 = np.random.randint(1,5, size=(3,4))
arr3

In [ ]:
arr4 = np.zeros(8).reshape(4,2)
arr4
arr4.ndim # check dimension

In [ ]:
arr4 = np.zeros(8,dtype = int).reshape(4,2)
arr4

In [ ]:
arr4 = np.ones(8).reshape(4,2)
arr4
#arr4.ndim # check dimension

# Eye Array or matrix

In [ ]:
np.eye(4,5)

In [ ]:
np.eye(3,4) # eye returns 1 in main diagonal as floating by default and the rest as 0 , rows are 3 and column are 4, by default k=0 means main diagonal

In [ ]:
np.eye(5) # 5 rows and if i did not mention columns then by default it will take rows number as a column number.

In [ ]:
print(np.eye(3,4,k=-1)) # Lower Diagonal  

In [ ]:
print(np.eye(3,4,k=1))  # Upper Diagonal

In [3]:
eyes = np.eye(4,5)
aar2 = np.arange(1,21).reshape(4,5)
print(eyes * aar2)

[[ 1.  0.  0.  0.  0.]
 [ 0.  7.  0.  0.  0.]
 [ 0.  0. 13.  0.  0.]
 [ 0.  0.  0. 19.  0.]]


# Dot Product of two array or matrix

In [ ]:
g,e =np.arange(3),np.arange(3,6)
print(g)
print(e)    # One way np.dot(agrument1,agrument2)
np.dot(g,e) # One Dimensinal dot product in which Every elememts gets multiplied with other element of same index and then all the results ofmultiplicaton gets add.

In [5]:
h,i = np.arange(12).reshape(3,4), np.arange(12).reshape(4,3)
print(h)
print()
print(i)
print()
h@i  # Two Dimension dot product, Rule 1: The column of the first array or matrix should match with the row of the second array or matrix and the shape(row,column) of the result of the dot product of two matrix or array gonna be row of the first matrix and the column of the second matrix.

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]



array([[ 42,  48,  54],
       [114, 136, 158],
       [186, 224, 262]])

In [ ]:
g,e =np.arange(3),np.arange(3,6)
print(g)
print(e)
g@e # Another python new version way for dot product agrument1*agrument2

# Cross Product of Two Array or Matrix

In [6]:
g,e =np.arange(3),np.arange(3,6)
print(g)
print(e)
np.cross(g,e) # One dimesion cross product , see both array as a combined matrix, take perpendicular of 0th row and 0th column and then skip that row and column(becuase of one dimension array or matrix skip only column but in two dimension array skip both perpendicular row and column) and then do the cross multiply and then minus the two values(i-j+k), second perpendicular gonna be minus due to -j, e.g -(4-2)=-2

[0 1 2]
[3 4 5]


array([-3,  6, -3])

In [10]:
h,i = np.arange(4).reshape(2,2), np.arange(4,8).reshape(2,2)
print(h)
print()
print(i)
print()
print(np.cross(h,i))  # Cross product of the two dimension array.

[[0 1]
 [2 3]]

[[4 5]
 [6 7]]

[-4 -4]


# Identity Array or matrix

In [ ]:
print(np.identity(3))  # An identity array is a square matrix with all the main diagonal elements as 1 and the rest as 0 .The default type of elements is float.

In [ ]:
print(np.identity(3, int)) 

In [ ]:
print(np.identity(3).ndim)

In [ ]:
np.linspace(2.0, 3.0, num=5, retstep=True, endpoint=False) # Return evenly spaced numbers over a specified interval.

In [ ]:
arr = np.array([[2,3],[6,9],[45,87]]) 
arr.size # gives no of data in array

In [ ]:
arr = np.array([[2,3],[6,9],[45,87]]) 
len(arr) # gives length of array

In [ ]:
arr3_t = arr3.T # Transpose
arr3_t

In [ ]:
arr1=np.arange(1,21).reshape(4,5)
arr1

In [ ]:
b=arr1[2:3,3:4] # slicing in array
print(b)

In [ ]:
arr1 + 1 # Vectorization

In [ ]:
import numpy as np
ardv1=np.random.randint(1,11,size=(2,5))
ardv2=np.random.randint(21,31,size=(2,5))
print(ardv1)
print()
print(ardv2)

In [ ]:
ardv1 + ardv2    # Vectorization or Broadcasitng

# Broadcasting

In [ ]:
ab = np.array([1,2,3,5,6]) 
ac = np.array([4,7,2,5,7])
print(ab)
print()
print(ac)
print()               # Rule 1 satisfied
print(np.add(ab,ac))  # Rule 1: In arithmetic operations both the arrays must have same shape.

In [ ]:
ab = np.array([1,2,3,5,6])   # Rule 2 satisfied
ad = np.array([6]) 
print(ab)
print()
print(ad)
print()
print(np.add(ab,ad))  # Rule 2: If both the shape are different, then anyone of them(rows and column) must be equal  to 1.

In [ ]:
ab = np.array([[1,2,3,5,6],[3,4,6,8,8,],[2,46,7,4,3]])
ad = np.array([[6,68,9,6,7],[7,2,4,6,7]])
print(ab+ad) # Rule 3: If rule 1 and rule 2 is not satisfied then it throws broadcasting error.

In [ ]:
num1 = np.array([[3,5,6],[3,3,6],[2,5,2]])
num2 = np.array([9,7,4])  # Rule 2: If the shape of the two arrays does not match in any dimension, the array with shape equal to 1 in that dimension is stretched to match the other shape.
#np.add(num1,num2) # gives broadcast shape error(Same thing as above rule 2 with another example).
print(num1)  # Rule 2 satisfied
print()
print(num2)
print()
print(num1 + num2) 

In [ ]:
num3 = np.arange(4).reshape(4,1)  # Rule 2 satisfied.
num4 = np.arange(4)
print(num3)
print()
print(num4)
print()
print(num3 + num4)

In [ ]:
ardvv = np.array([1,2,3,4,5,6,])
arvind = ardvv.reshape(2,3) # Reshape, for converting one dimensional array into two dimensional array, when this happen in numpy original 1 dimension array gets deleted and new array gets created with 2 dimension and due to python name binding property name of the variable which store that array gonna be same for the new array as well.
print(arvind)

In [ ]:
ardv1.reshape(10) # Reshape two dimensional array into one dimensional array.

In [ ]:
iron = np.random.randn(16) # Gives one dimensional array
iron

In [ ]:
hulk = np.random.randn(16).reshape(2,4,2) # Reshaping one dimensional array into three dimensional array
hulk

In [ ]:
np.random.randn(16).reshape(2,4,2).reshape(16) # Reshaping three dimensional array into one dimensional array
# we can do this way

In [ ]:
hulk.reshape(16) # or we can do this way both gives same result, value gonna be different because of use of random.randn, which gives random values.

In [ ]:
arvind.shape

In [ ]:
arvind.sum() # total summation of the elemnts in array

In [ ]:
arvind.sum(axis=1) # for horizontal summation

In [ ]:
arvind.sum(axis = 0) # for vertical summation

In [ ]:
c = np.concatenate((ardv1,ardv2),axis = 0) #Concatenation in array , By default axis = 0 vertical stacking or concatenation (column wise).
print(c)

In [ ]:
c = np.concatenate((ardv1,ardv2),axis = 1) #Concatenation in array ,axis = 1 horizontal stacking or concatenation (row wise) makes two element.
print(c)

In [ ]:
x = np.array([1,2,3], float)
y = x
x[0] = 100
z = x.copy() # The copy function can be used to create a new, separate copy of an array in memory.
x[0] = 1000 # Changes made in original array will not affect new array.
print(x)
print(y)
print(z) # Changes made in original array will not affect new array.

In [ ]:
x.tolist()  # Lists can also be created from arrays.
list(x)

In [ ]:
v = x.tostring() # Convert array to string in binary language(not readable for human).
v

In [ ]:
np.fromstring(v) # Convert string to array(readable for human being).

In [ ]:
print(x)
x.fill(0) # To fill an array with a single value.
print(x)

In [ ]:
arvind.flatten() # One-dimensional versions of multi-dimensional arrays can be generated with flatten.

In [ ]:
z=z[:,np.newaxis] # Convert 1 D array into column vector, add axis after original 1 D array (original_length, 1).
print(z)
z.shape

In [ ]:
x=x[np.newaxis,:] # Convert 1 D array into row vector, add axis before original 1 D array (1, original_length).
print(x)
x.shape

In [ ]:
ardv1.max() # Gives maximum number from array. (Aggreagate Function)

In [ ]:
ardv1.min() # Gives minimum number from array. (Aggreagate Function)

In [ ]:
ardv1.max(axis=0) # Gives maximum number from verticallly (column wise). (Aggreagate Function)

In [ ]:
ardv1.max(axis=1) # Gives maximum number from horizontally (row wise). (Aggreagate Function)

In [ ]:
ardv1.mean() # (Aggreagate Function)

In [ ]:
ardv1.var() # (Aggreagate Function)

In [ ]:
ardv1.std() # (Aggreagate Function)

# Numpy Function

In [ ]:
f = np.array([33,44,22,345,55,22,5,666,44,66,221,67,53])

In [ ]:
np.mean(f)

In [ ]:
np.median(f)

In [ ]:
q1 = np.quantile(f,0.25)
q3 = np.quantile(f,0.75)
iqr = q3 - q1
print(q3)
print(q1)
print(iqr)

In [ ]:
upper_range = q3 + 1.5*iqr
lower_range = q1 - 1.5*iqr
print(upper_range)
print(lower_range)

In [ ]:
g = np.array([[2,6,2,5,7],[9,7,1,3,5]])

In [ ]:
np.corrcoef(g) 

In [ ]:
np.cov(g) 

# Math Function

In [ ]:
np.sin(48)

In [ ]:
np.cos(34)

In [ ]:
np.tan(96)

In [ ]:
np.log(44)

In [ ]:
np.log10(55)

In [ ]:
np.sqrt(9)

# Boolean indexing

In [3]:
num1 = np.array([[3,5,6],[3,3,6],[2,5,2]])
num1 > 4

array([[False,  True,  True],
       [False, False,  True],
       [False,  True, False]])

In [4]:
num1[num1>4]

array([5, 6, 6, 5])

In [5]:
num1[num1 % 2==0]

array([6, 6, 2, 2])